### ISSUE TITLE
[ Feature Request ] spelling before sending a message

### ISSUE THREAD

**Issue by Dallran** [julian-alarcon/prospect-mail#15]
Would be good to have a spelling button (spanish or english)

https://support.office.com/en-us/article/check-spelling-before-sending-a-message-620b24fc-9cc5-4a2f-a26b-9ff4e02cc193

**Comment by jvacek** [comment]
I'd like to hop on this and add that the app should enable the electron spellchecker within text fields. https://github.com/electron/electron/pull/20692

**Comment by antonical** [comment]
In the version I am running prospect-mail      0.2.0 spellings are highlighted but there is no right click to action them. 

Cheers

**Comment by haukened** [comment]
> In the version I am running prospect-mail 0.2.0 spellings are highlighted but there is no right click to action them.
> 
> Cheers

i added the right click action, however this does not force spell check before sending.

**Comment by julian-alarcon** [comment]
Fixed by https://github.com/julian-alarcon/prospect-mail/pull/128
I know that it's not the same as the title, but I think that it's the best and easy approach for now.

**Comment by fried-eggz** [comment]
This is not fixed. Since there is no way to select a language this only partially resolves the issue. If you use any other language than English you will get all your words underlined with no way to change language or turn the spellchecker completely off.

**Comment by quintanaplaca** [comment]
Hello. @julian-alarcon, please, look for this when you have time. The @fried-eggz comments make sense.

**Comment by fried-eggz** [comment]
This is NOT fixed and should nor be closed. There is no way for users of other languages to spellcheck their languages. The web app from Microsoft makes it ease to change the language.

As its stands now. Users of other languages than English cannot use the software properly. Please prioritize this.
