### ISSUE TITLE
No right click in message body

### ISSUE THREAD

**Issue by grantthomas** [julian-alarcon/prospect-mail#173]
I've recently updated to 0.3 from the 0.1.2 release.

Both versions I'm unable to right click in message bodies.

I can right click on:

- left bar folder entires
- emails in the middle pane
- names in the TO and CC fields of new/reply/forward

I cannot right click:

- Message body in reading pane / preview or pop out window in either view only or editable messages

Settings:
Logged in through application UI.
Settings file contents is blank: {}

OS: Pop OS 21.04
Env: KDE 5.21.4, SDDM
Release: 0.3 deb : https://github.com/julian-alarcon/prospect-mail/releases/download/v0.3.0/prospect-mail_0.3.0_amd64.deb

**Comment by codebori** [comment]
I have the same issue.

Prospect Mail 0.3.0-275
OpenSuse Tumbleweed
KDE 5.22.4, SDDM


I also saw a similar issue here: https://github.com/julian-alarcon/prospect-mail/issues/27

**Comment by DenisBY** [comment]
The same on Manjaro and app version 0.3.0

**Comment by julian-alarcon** [comment]
There are some implementations on the internet.
https://stackoverflow.com/questions/63379503/electron-js-with-the-right-click-be-able-to-perform-a-copy-and-cut-if-a-sel
https://github.com/sindresorhus/electron-context-menu

Maybe someone could work on this.

**Comment by MagiusCHE** [comment]
should include #122 too

**Comment by MagiusCHE** [comment]
@julian-alarcon can you assign this to me? ( so i can found in my Issue tab :-) )

**Comment by MagiusCHE** [comment]
Done! It will be in the next PR #201
![immagine](https://user-images.githubusercontent.com/46496052/146260010-dfb72626-4f6f-47fb-a8b3-ff7f9a409e3e.png)

**Comment by grantthomas** [comment]
Thanks for the work so far @MagiusCHE, but this issue is still happening for my system after a full OS reinstall.

I am only able to right-click when replying to a message, and only when there is a spelling mistake noticed.
Even then, I do not see the full list of options you show in your screenshot.
![image](https://user-images.githubusercontent.com/21267386/152665557-ac01d01b-5850-4984-8b21-30527ac6950e.png)

However, I cannot right-click any other text in the message pane, whether in an email I am reading or in a response I am writing.

I would send a screenshot of other interactions, but with nothing happening I don't think it would be of any use.
If I run it from the console, these are the output
![image](https://user-images.githubusercontent.com/21267386/152665608-e26be386-1b09-4ad9-a793-bf50fcf9cf36.png)

I have installed the .deb package 0.4.0 that references #128, but do not see this issue, #173 in the changelist
from here: [v0.4.0 release](https://github.com/julian-alarcon/prospect-mail/releases/download/v0.4.0/prospect-mail_0.4.0_amd64.deb)
![image](https://user-images.githubusercontent.com/21267386/152665630-910b675a-f3de-4ad7-b74e-641c79e4fc30.png)

As a reference, in the Outlook.com PWA, I am seeing these behaviors when editing:
![image](https://user-images.githubusercontent.com/21267386/152665717-a28789ea-15fc-4b59-9c48-de98e143fc3e.png)
![image](https://user-images.githubusercontent.com/21267386/152665794-76a2106f-d71e-4589-872d-b01cce163033.png)


Thanks again for putting your time and effort into improving Prospect

**Comment by MagiusCHE** [comment]
@grantthomas can you try one my releases? https://github.com/MagiusCHE/prospect-mail/releases/tag/v0.5.0-beta-tmp
i guess this feature is not merged in mainline.

**Comment by grantthomas** [comment]
Hi @MagiusCHE 

Your 0.5.0-beta build works for me.
I see this behavior in the message pane

reading email
On hilight
![image](https://user-images.githubusercontent.com/21267386/152818315-1621136f-ef6c-40de-9923-d61427a20d90.png)

on right-click
![image](https://user-images.githubusercontent.com/21267386/152818372-34d2ec05-a159-4fcd-a083-8ce659fd4629.png)

Composing email
right click on known word
![image](https://user-images.githubusercontent.com/21267386/152818512-4b7289a0-15bd-47a4-a6cd-07a94eeec28b.png)

Right click on misspelled word
![image](https://user-images.githubusercontent.com/21267386/152818588-9cf9eb87-ee9a-4ef6-89a6-2758856c23cd.png)


This is fantastic, it seems minor but can be important to daily use.

**Comment by DenisBY** [comment]
@MagiusCHE I couldn't find how to fill an issue in your repo. We have 2FA enabled and your version is failing to show the MFA page.

**Comment by DenisBY** [comment]
@MagiusCHE but I don't have an issue with 0.4.0. Only with your 0.5.0-beta.

**Comment by MagiusCHE** [comment]
> @MagiusCHE but I don't have an issue with 0.4.0. Only with your 0.5.0-beta.

Ive enabled issue on my fork. U can writer there.
